# Generated by Django 2.2 on 2021-10-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='contactNumber',
            field=models.IntegerField(default=None),
        ),
    ]
