# Generated by Django 2.2 on 2021-11-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20211101_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='contactNumber',
            field=models.CharField(max_length=20),
        ),
    ]
